application: ragetube
version: 2
runtime: python
api_version: 1

handlers:

- url: /img
  static_dir: img 

- url: /js
  static_dir: js 

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
    
- url: /.*
  script: main.py
